# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alvar_000\PycharmProjects\algebra_1\interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TareaAlgebra(object):
    def setupUi(self, TareaAlgebra):
        TareaAlgebra.setObjectName("TareaAlgebra")
        TareaAlgebra.resize(539, 639)
        self.centralwidget = QtWidgets.QWidget(TareaAlgebra)
        self.centralwidget.setObjectName("centralwidget")
        self.FilasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FilasGroupBox.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.FilasGroupBox.setObjectName("FilasGroupBox")
        self.filas2 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas2.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.filas2.setChecked(True)
        self.filas2.setObjectName("filas2")
        self.filas3 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas3.setGeometry(QtCore.QRect(50, 10, 31, 17))
        self.filas3.setObjectName("filas3")
        self.filas4 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas4.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.filas4.setObjectName("filas4")
        self.filas5 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas5.setGeometry(QtCore.QRect(130, 10, 41, 17))
        self.filas5.setObjectName("filas5")
        self.ColumnasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ColumnasGroupBox.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.ColumnasGroupBox.setObjectName("ColumnasGroupBox")
        self.col2 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col2.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.col2.setChecked(True)
        self.col2.setObjectName("col2")
        self.col3 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col3.setGeometry(QtCore.QRect(50, 10, 31, 17))
        self.col3.setObjectName("col3")
        self.col4 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col4.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.col4.setObjectName("col4")
        self.col5 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col5.setGeometry(QtCore.QRect(130, 10, 41, 17))
        self.col5.setObjectName("col5")
        self.MatrizGropBox = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox.setGeometry(QtCore.QRect(220, 0, 301, 111))
        self.MatrizGropBox.setObjectName("MatrizGropBox")
        self.f1c1a = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c1a.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.f1c1a.setText("")
        self.f1c1a.setObjectName("f1c1a")
        self.f1c1b = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c1b.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.f1c1b.setText("")
        self.f1c1b.setObjectName("f1c1b")
        self.f1c2a = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c2a.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.f1c2a.setText("")
        self.f1c2a.setObjectName("f1c2a")
        self.f1c2b = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c2b.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.f1c2b.setText("")
        self.f1c2b.setObjectName("f1c2b")
        self.f1c3a = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c3a.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.f1c3a.setText("")
        self.f1c3a.setObjectName("f1c3a")
        self.f1c3b = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c3b.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.f1c3b.setText("")
        self.f1c3b.setObjectName("f1c3b")
        self.f1c4a = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c4a.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.f1c4a.setText("")
        self.f1c4a.setObjectName("f1c4a")
        self.f1c4b = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c4b.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.f1c4b.setText("")
        self.f1c4b.setObjectName("f1c4b")
        self.f1c5a = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c5a.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.f1c5a.setText("")
        self.f1c5a.setObjectName("f1c5a")
        self.f1c5b = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.f1c5b.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.f1c5b.setText("")
        self.f1c5b.setObjectName("f1c5b")
        self.line = QtWidgets.QFrame(self.MatrizGropBox)
        self.line.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_2.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_3.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_4.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_5.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.MatrizGropBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_2.setGeometry(QtCore.QRect(220, 120, 301, 111))
        self.MatrizGropBox_2.setObjectName("MatrizGropBox_2")
        self.f2c1a = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c1a.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.f2c1a.setText("")
        self.f2c1a.setObjectName("f2c1a")
        self.f2c1b = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c1b.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.f2c1b.setText("")
        self.f2c1b.setObjectName("f2c1b")
        self.f2c2a = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c2a.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.f2c2a.setText("")
        self.f2c2a.setObjectName("f2c2a")
        self.f2c2b = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c2b.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.f2c2b.setText("")
        self.f2c2b.setObjectName("f2c2b")
        self.f2c3a = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c3a.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.f2c3a.setText("")
        self.f2c3a.setObjectName("f2c3a")
        self.f2c3b = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c3b.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.f2c3b.setText("")
        self.f2c3b.setObjectName("f2c3b")
        self.f2c4a = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c4a.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.f2c4a.setText("")
        self.f2c4a.setObjectName("f2c4a")
        self.f2c4b = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c4b.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.f2c4b.setText("")
        self.f2c4b.setObjectName("f2c4b")
        self.f2c5a = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c5a.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.f2c5a.setText("")
        self.f2c5a.setObjectName("f2c5a")
        self.f2c5b = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.f2c5b.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.f2c5b.setText("")
        self.f2c5b.setObjectName("f2c5b")
        self.line_6 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_6.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_7.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_8.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_9.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_10.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.MatrizGropBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_3.setGeometry(QtCore.QRect(220, 240, 301, 111))
        self.MatrizGropBox_3.setObjectName("MatrizGropBox_3")
        self.f3c1a = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c1a.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.f3c1a.setText("")
        self.f3c1a.setObjectName("f3c1a")
        self.f3c1b = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c1b.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.f3c1b.setText("")
        self.f3c1b.setObjectName("f3c1b")
        self.f3c2a = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c2a.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.f3c2a.setText("")
        self.f3c2a.setObjectName("f3c2a")
        self.f3c2b = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c2b.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.f3c2b.setText("")
        self.f3c2b.setObjectName("f3c2b")
        self.f3c3a = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c3a.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.f3c3a.setText("")
        self.f3c3a.setObjectName("f3c3a")
        self.f3c3b = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c3b.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.f3c3b.setText("")
        self.f3c3b.setObjectName("f3c3b")
        self.f3c4a = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c4a.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.f3c4a.setText("")
        self.f3c4a.setObjectName("f3c4a")
        self.f3c4b = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c4b.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.f3c4b.setText("")
        self.f3c4b.setObjectName("f3c4b")
        self.f3c5a = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c5a.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.f3c5a.setText("")
        self.f3c5a.setObjectName("f3c5a")
        self.f3c5b = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.f3c5b.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.f3c5b.setText("")
        self.f3c5b.setObjectName("f3c5b")
        self.line_11 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_11.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_12.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_13.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_14.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_15.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.MatrizGropBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_4.setGeometry(QtCore.QRect(220, 480, 301, 111))
        self.MatrizGropBox_4.setObjectName("MatrizGropBox_4")
        self.f5c1a = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c1a.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.f5c1a.setText("")
        self.f5c1a.setObjectName("f5c1a")
        self.f5c1b = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c1b.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.f5c1b.setText("")
        self.f5c1b.setObjectName("f5c1b")
        self.f5c2a = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c2a.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.f5c2a.setText("")
        self.f5c2a.setObjectName("f5c2a")
        self.f5c2b = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c2b.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.f5c2b.setText("")
        self.f5c2b.setObjectName("f5c2b")
        self.f5c3a = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c3a.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.f5c3a.setText("")
        self.f5c3a.setObjectName("f5c3a")
        self.f5c3b = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c3b.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.f5c3b.setText("")
        self.f5c3b.setObjectName("f5c3b")
        self.f5c4a = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c4a.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.f5c4a.setText("")
        self.f5c4a.setObjectName("f5c4a")
        self.f5c4b = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c4b.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.f5c4b.setText("")
        self.f5c4b.setObjectName("f5c4b")
        self.f5c5a = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c5a.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.f5c5a.setText("")
        self.f5c5a.setObjectName("f5c5a")
        self.f5c5b = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.f5c5b.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.f5c5b.setText("")
        self.f5c5b.setObjectName("f5c5b")
        self.line_21 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_21.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_22.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_23.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_24.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_25 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_25.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.MatrizGropBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_5.setGeometry(QtCore.QRect(220, 360, 301, 111))
        self.MatrizGropBox_5.setObjectName("MatrizGropBox_5")
        self.f4c1a = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c1a.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.f4c1a.setText("")
        self.f4c1a.setObjectName("f4c1a")
        self.f4c1b = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c1b.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.f4c1b.setText("")
        self.f4c1b.setObjectName("f4c1b")
        self.f4c2a = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c2a.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.f4c2a.setText("")
        self.f4c2a.setObjectName("f4c2a")
        self.f4c2b = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c2b.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.f4c2b.setText("")
        self.f4c2b.setObjectName("f4c2b")
        self.f4c3a = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c3a.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.f4c3a.setText("")
        self.f4c3a.setObjectName("f4c3a")
        self.f4c3b = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c3b.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.f4c3b.setText("")
        self.f4c3b.setObjectName("f4c3b")
        self.f4c4a = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c4a.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.f4c4a.setText("")
        self.f4c4a.setObjectName("f4c4a")
        self.f4c4b = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c4b.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.f4c4b.setText("")
        self.f4c4b.setObjectName("f4c4b")
        self.f4c5a = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c5a.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.f4c5a.setText("")
        self.f4c5a.setObjectName("f4c5a")
        self.f4c5b = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.f4c5b.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.f4c5b.setText("")
        self.f4c5b.setObjectName("f4c5b")
        self.line_26 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_26.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_27.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_28.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_29.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_30.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 181, 331))
        self.groupBox.setObjectName("groupBox")
        self.FilaxfilasGroupBox = QtWidgets.QGroupBox(self.groupBox)
        self.FilaxfilasGroupBox.setGeometry(QtCore.QRect(10, 20, 161, 81))
        self.FilaxfilasGroupBox.setObjectName("FilaxfilasGroupBox")
        self.filaA1 = QtWidgets.QLineEdit(self.FilaxfilasGroupBox)
        self.filaA1.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.filaA1.setObjectName("filaA1")
        self.filaA2 = QtWidgets.QLineEdit(self.FilaxfilasGroupBox)
        self.filaA2.setGeometry(QtCore.QRect(110, 20, 41, 20))
        self.filaA2.setObjectName("filaA2")
        self.RealizarTipoA = QtWidgets.QPushButton(self.FilaxfilasGroupBox)
        self.RealizarTipoA.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.RealizarTipoA.setObjectName("RealizarTipoA")
        self.label = QtWidgets.QLabel(self.FilaxfilasGroupBox)
        self.label.setGeometry(QtCore.QRect(60, 20, 41, 16))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 161, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_2.setObjectName("label_2")
        self.filaB = QtWidgets.QLineEdit(self.groupBox_3)
        self.filaB.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.filaB.setObjectName("filaB")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.constanteB = QtWidgets.QLineEdit(self.groupBox_3)
        self.constanteB.setGeometry(QtCore.QRect(60, 40, 21, 20))
        self.constanteB.setObjectName("constanteB")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.label_4.setObjectName("label_4")
        self.RealizarTipoB = QtWidgets.QPushButton(self.groupBox_3)
        self.RealizarTipoB.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.RealizarTipoB.setObjectName("RealizarTipoB")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 220, 161, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(130, 20, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(100, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(40, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.filaC1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.filaC1.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.filaC1.setObjectName("filaC1")
        self.constanteC = QtWidgets.QLineEdit(self.groupBox_4)
        self.constanteC.setGeometry(QtCore.QRect(70, 40, 21, 20))
        self.constanteC.setObjectName("constanteC")
        self.filaC2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.filaC2.setGeometry(QtCore.QRect(130, 40, 21, 20))
        self.filaC2.setObjectName("filaC2")
        self.RealizarTipoC = QtWidgets.QPushButton(self.groupBox_4)
        self.RealizarTipoC.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.RealizarTipoC.setObjectName("RealizarTipoC")
        self.nuevaMatrizButt = QtWidgets.QPushButton(self.centralwidget)
        self.nuevaMatrizButt.setGeometry(QtCore.QRect(20, 440, 141, 23))
        self.nuevaMatrizButt.setObjectName("nuevaMatrizButt")
        self.sResutadosButt = QtWidgets.QPushButton(self.centralwidget)
        self.sResutadosButt.setGeometry(QtCore.QRect(20, 480, 141, 23))
        self.sResutadosButt.setObjectName("sResutadosButt")
        TareaAlgebra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TareaAlgebra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 21))
        self.menubar.setObjectName("menubar")
        TareaAlgebra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TareaAlgebra)
        self.statusbar.setObjectName("statusbar")
        TareaAlgebra.setStatusBar(self.statusbar)

        self.retranslateUi(TareaAlgebra)
        QtCore.QMetaObject.connectSlotsByName(TareaAlgebra)

    def retranslateUi(self, TareaAlgebra):
        _translate = QtCore.QCoreApplication.translate
        TareaAlgebra.setWindowTitle(_translate("TareaAlgebra", "MainWindow"))
        self.FilasGroupBox.setTitle(_translate("TareaAlgebra", "Filas"))
        self.filas2.setText(_translate("TareaAlgebra", "2"))
        self.filas3.setText(_translate("TareaAlgebra", "3"))
        self.filas4.setText(_translate("TareaAlgebra", "4"))
        self.filas5.setText(_translate("TareaAlgebra", "5"))
        self.ColumnasGroupBox.setTitle(_translate("TareaAlgebra", "Columnas"))
        self.col2.setText(_translate("TareaAlgebra", "2"))
        self.col3.setText(_translate("TareaAlgebra", "3"))
        self.col4.setText(_translate("TareaAlgebra", "4"))
        self.col5.setText(_translate("TareaAlgebra", "5"))
        self.MatrizGropBox.setTitle(_translate("TareaAlgebra", "Fila 1"))
        self.MatrizGropBox_2.setTitle(_translate("TareaAlgebra", "Fila 2"))
        self.MatrizGropBox_3.setTitle(_translate("TareaAlgebra", "Fila 3"))
        self.MatrizGropBox_4.setTitle(_translate("TareaAlgebra", "Fila 5"))
        self.MatrizGropBox_5.setTitle(_translate("TareaAlgebra", "Fila 4"))
        self.groupBox.setTitle(_translate("TareaAlgebra", "Operaciones Elementales"))
        self.FilaxfilasGroupBox.setTitle(_translate("TareaAlgebra", "Cambiar fila por fila"))
        self.RealizarTipoA.setText(_translate("TareaAlgebra", "Realizar"))
        self.label.setText(_translate("TareaAlgebra", "<----->"))
        self.groupBox_3.setTitle(_translate("TareaAlgebra", "Fila por Constante"))
        self.label_2.setText(_translate("TareaAlgebra", "Fila"))
        self.label_3.setText(_translate("TareaAlgebra", "*"))
        self.label_4.setText(_translate("TareaAlgebra", "Constante"))
        self.RealizarTipoB.setText(_translate("TareaAlgebra", "Realizar"))
        self.groupBox_4.setTitle(_translate("TareaAlgebra", "Tipo C"))
        self.label_5.setText(_translate("TareaAlgebra", "Fila"))
        self.label_6.setText(_translate("TareaAlgebra", "Fila"))
        self.label_7.setText(_translate("TareaAlgebra", "Constante"))
        self.label_8.setText(_translate("TareaAlgebra", "*"))
        self.label_9.setText(_translate("TareaAlgebra", "+"))
        self.RealizarTipoC.setText(_translate("TareaAlgebra", "Realizar"))
        self.nuevaMatrizButt.setText(_translate("TareaAlgebra", "Nueva Matriz"))
        self.sResutadosButt.setText(_translate("TareaAlgebra", "Secuencia de Resultados"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TareaAlgebra = QtWidgets.QMainWindow()
    ui = Ui_TareaAlgebra()
    ui.setupUi(TareaAlgebra)
    TareaAlgebra.show()
    sys.exit(app.exec_())