# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TareaAlgebra(object):
    def setupUi(self, TareaAlgebra):
        TareaAlgebra.setObjectName("TareaAlgebra")
        TareaAlgebra.resize(539, 639)
        self.centralwidget = QtWidgets.QWidget(TareaAlgebra)
        self.centralwidget.setObjectName("centralwidget")
        self.FilasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FilasGroupBox.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.FilasGroupBox.setObjectName("FilasGroupBox")
        self.filas2 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas2.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.filas2.setChecked(True)
        self.filas2.setObjectName("filas2")
        self.filas3 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas3.setGeometry(QtCore.QRect(50, 10, 31, 17))
        self.filas3.setObjectName("filas3")
        self.filas4 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas4.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.filas4.setObjectName("filas4")
        self.filas5 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas5.setGeometry(QtCore.QRect(130, 10, 41, 17))
        self.filas5.setObjectName("filas5")
        self.ColumnasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ColumnasGroupBox.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.ColumnasGroupBox.setObjectName("ColumnasGroupBox")
        self.col2 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col2.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.col2.setChecked(True)
        self.col2.setObjectName("col2")
        self.col3 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col3.setGeometry(QtCore.QRect(50, 10, 31, 17))
        self.col3.setObjectName("col3")
        self.col4 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col4.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.col4.setObjectName("col4")
        self.col5 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col5.setGeometry(QtCore.QRect(130, 10, 41, 17))
        self.col5.setObjectName("col5")
        self.MatrizGropBox = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox.setGeometry(QtCore.QRect(220, 0, 301, 111))
        self.MatrizGropBox.setObjectName("MatrizGropBox")
        self.lineEdit = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.MatrizGropBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.line = QtWidgets.QFrame(self.MatrizGropBox)
        self.line.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_2.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_3.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_4.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.MatrizGropBox)
        self.line_5.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.MatrizGropBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_2.setGeometry(QtCore.QRect(220, 120, 301, 111))
        self.MatrizGropBox_2.setObjectName("MatrizGropBox_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.MatrizGropBox_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.lineEdit_20.setText("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.line_6 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_6.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_7.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_8.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_9.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.MatrizGropBox_2)
        self.line_10.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.MatrizGropBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_3.setGeometry(QtCore.QRect(220, 240, 301, 111))
        self.MatrizGropBox_3.setObjectName("MatrizGropBox_3")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_21.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_22.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_23.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_24.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_25.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_26.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_27.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_28.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_29.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.lineEdit_29.setText("")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.MatrizGropBox_3)
        self.lineEdit_30.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.line_11 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_11.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_12.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_13.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_14.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.MatrizGropBox_3)
        self.line_15.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.MatrizGropBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_4.setGeometry(QtCore.QRect(220, 480, 301, 111))
        self.MatrizGropBox_4.setObjectName("MatrizGropBox_4")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_41.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.lineEdit_41.setText("")
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_42.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.lineEdit_42.setText("")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_43.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.lineEdit_43.setText("")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_44.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.lineEdit_44.setText("")
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_45.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.lineEdit_45.setText("")
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_46.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.lineEdit_46.setText("")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_47.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.lineEdit_47.setText("")
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_48.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.lineEdit_48.setText("")
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_49.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.lineEdit_49.setText("")
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.MatrizGropBox_4)
        self.lineEdit_50.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.lineEdit_50.setText("")
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.line_21 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_21.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_22.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_23.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_24.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_25 = QtWidgets.QFrame(self.MatrizGropBox_4)
        self.line_25.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.MatrizGropBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.MatrizGropBox_5.setGeometry(QtCore.QRect(220, 360, 301, 111))
        self.MatrizGropBox_5.setObjectName("MatrizGropBox_5")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_51.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.lineEdit_51.setText("")
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_52.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.lineEdit_52.setText("")
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_53.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.lineEdit_53.setText("")
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_54.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.lineEdit_54.setText("")
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_55.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.lineEdit_55.setText("")
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_56.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.lineEdit_56.setText("")
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_57.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.lineEdit_57.setText("")
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_58.setGeometry(QtCore.QRect(200, 80, 31, 20))
        self.lineEdit_58.setText("")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_59.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.lineEdit_59.setText("")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.MatrizGropBox_5)
        self.lineEdit_60.setGeometry(QtCore.QRect(260, 80, 31, 20))
        self.lineEdit_60.setText("")
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.line_26 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_26.setGeometry(QtCore.QRect(20, 56, 31, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_27.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_28.setGeometry(QtCore.QRect(200, 60, 31, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_29.setGeometry(QtCore.QRect(140, 60, 31, 20))
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(self.MatrizGropBox_5)
        self.line_30.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 181, 331))
        self.groupBox.setObjectName("groupBox")
        self.FilaxfilasGroupBox = QtWidgets.QGroupBox(self.groupBox)
        self.FilaxfilasGroupBox.setGeometry(QtCore.QRect(10, 20, 161, 81))
        self.FilaxfilasGroupBox.setObjectName("FilaxfilasGroupBox")
        self.filaA1 = QtWidgets.QLineEdit(self.FilaxfilasGroupBox)
        self.filaA1.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.filaA1.setObjectName("filaA1")
        self.filaA2 = QtWidgets.QLineEdit(self.FilaxfilasGroupBox)
        self.filaA2.setGeometry(QtCore.QRect(110, 20, 41, 20))
        self.filaA2.setObjectName("filaA2")
        self.RealizarTipoA = QtWidgets.QPushButton(self.FilaxfilasGroupBox)
        self.RealizarTipoA.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.RealizarTipoA.setObjectName("RealizarTipoA")
        self.label = QtWidgets.QLabel(self.FilaxfilasGroupBox)
        self.label.setGeometry(QtCore.QRect(60, 20, 41, 16))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 161, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_2.setObjectName("label_2")
        self.filaB = QtWidgets.QLineEdit(self.groupBox_3)
        self.filaB.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.filaB.setObjectName("filaB")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.constanteB = QtWidgets.QLineEdit(self.groupBox_3)
        self.constanteB.setGeometry(QtCore.QRect(60, 40, 21, 20))
        self.constanteB.setObjectName("constanteB")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.label_4.setObjectName("label_4")
        self.RealizarTipoB = QtWidgets.QPushButton(self.groupBox_3)
        self.RealizarTipoB.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.RealizarTipoB.setObjectName("RealizarTipoB")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 220, 161, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(130, 20, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(100, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(40, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.filaC1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.filaC1.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.filaC1.setObjectName("filaC1")
        self.constanteC = QtWidgets.QLineEdit(self.groupBox_4)
        self.constanteC.setGeometry(QtCore.QRect(70, 40, 21, 20))
        self.constanteC.setObjectName("constanteC")
        self.filaC2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.filaC2.setGeometry(QtCore.QRect(130, 40, 21, 20))
        self.filaC2.setObjectName("filaC2")
        self.RealizarTipoC = QtWidgets.QPushButton(self.groupBox_4)
        self.RealizarTipoC.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.RealizarTipoC.setObjectName("RealizarTipoC")
        self.nuevaMatrizButt = QtWidgets.QPushButton(self.centralwidget)
        self.nuevaMatrizButt.setGeometry(QtCore.QRect(20, 440, 141, 23))
        self.nuevaMatrizButt.setObjectName("nuevaMatrizButt")
        self.sResutadosButt = QtWidgets.QPushButton(self.centralwidget)
        self.sResutadosButt.setGeometry(QtCore.QRect(20, 480, 141, 23))
        self.sResutadosButt.setObjectName("sResutadosButt")
        TareaAlgebra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TareaAlgebra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 21))
        self.menubar.setObjectName("menubar")
        TareaAlgebra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TareaAlgebra)
        self.statusbar.setObjectName("statusbar")
        TareaAlgebra.setStatusBar(self.statusbar)

        self.retranslateUi(TareaAlgebra)
        QtCore.QMetaObject.connectSlotsByName(TareaAlgebra)

    def retranslateUi(self, TareaAlgebra):
        _translate = QtCore.QCoreApplication.translate
        TareaAlgebra.setWindowTitle(_translate("TareaAlgebra", "MainWindow"))
        self.FilasGroupBox.setTitle(_translate("TareaAlgebra", "Filas"))
        self.filas2.setText(_translate("TareaAlgebra", "2"))
        self.filas3.setText(_translate("TareaAlgebra", "3"))
        self.filas4.setText(_translate("TareaAlgebra", "4"))
        self.filas5.setText(_translate("TareaAlgebra", "5"))
        self.ColumnasGroupBox.setTitle(_translate("TareaAlgebra", "Columnas"))
        self.col2.setText(_translate("TareaAlgebra", "2"))
        self.col3.setText(_translate("TareaAlgebra", "3"))
        self.col4.setText(_translate("TareaAlgebra", "4"))
        self.col5.setText(_translate("TareaAlgebra", "5"))
        self.MatrizGropBox.setTitle(_translate("TareaAlgebra", "Fila 1"))
        self.MatrizGropBox_2.setTitle(_translate("TareaAlgebra", "Fila 2"))
        self.MatrizGropBox_3.setTitle(_translate("TareaAlgebra", "Fila 3"))
        self.MatrizGropBox_4.setTitle(_translate("TareaAlgebra", "Fila 5"))
        self.MatrizGropBox_5.setTitle(_translate("TareaAlgebra", "Fila 4"))
        self.groupBox.setTitle(_translate("TareaAlgebra", "Operaciones Elementales"))
        self.FilaxfilasGroupBox.setTitle(_translate("TareaAlgebra", "Cambiar fila por fila"))
        self.RealizarTipoA.setText(_translate("TareaAlgebra", "Realizar"))
        self.label.setText(_translate("TareaAlgebra", "<----->"))
        self.groupBox_3.setTitle(_translate("TareaAlgebra", "Fila por Constante"))
        self.label_2.setText(_translate("TareaAlgebra", "Fila"))
        self.label_3.setText(_translate("TareaAlgebra", "*"))
        self.label_4.setText(_translate("TareaAlgebra", "Constante"))
        self.RealizarTipoB.setText(_translate("TareaAlgebra", "Realizar"))
        self.groupBox_4.setTitle(_translate("TareaAlgebra", "Tipo C"))
        self.label_5.setText(_translate("TareaAlgebra", "Fila"))
        self.label_6.setText(_translate("TareaAlgebra", "Fila"))
        self.label_7.setText(_translate("TareaAlgebra", "Constante"))
        self.label_8.setText(_translate("TareaAlgebra", "*"))
        self.label_9.setText(_translate("TareaAlgebra", "+"))
        self.RealizarTipoC.setText(_translate("TareaAlgebra", "Realizar"))
        self.nuevaMatrizButt.setText(_translate("TareaAlgebra", "Nueva Matriz"))
        self.sResutadosButt.setText(_translate("TareaAlgebra", "Secuencia de Resultados"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TareaAlgebra = QtWidgets.QMainWindow()
    ui = Ui_TareaAlgebra()
    ui.setupUi(TareaAlgebra)
    TareaAlgebra.show()
    sys.exit(app.exec_())

