# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from fractions import Fraction

from PyQt5 import QtCore, QtGui, QtWidgets

from OperacionesElementales import *

from crearSecuenciaResultados import *


class Ui_TareaAlgebra(object):

    matrizEnInterfaz = []
    matrizActiva = []
    matrizReal = []
    filas = 5
    columnas = 5

    def setupUi(self, TareaAlgebra):
        TareaAlgebra.setObjectName("TareaAlgebra")
        TareaAlgebra.resize(524, 551)
        self.centralwidget = QtWidgets.QWidget(TareaAlgebra)
        self.centralwidget.setObjectName("centralwidget")
        self.FilasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FilasGroupBox.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.FilasGroupBox.setObjectName("FilasGroupBox")
        self.filas2 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas2.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.filas2.setChecked(False)
        self.filas2.setObjectName("filas2")
        self.filas3 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas3.setGeometry(QtCore.QRect(50, 10, 31, 17))
        self.filas3.setObjectName("filas3")
        self.filas4 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas4.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.filas4.setObjectName("filas4")
        self.filas5 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas5.setGeometry(QtCore.QRect(130, 10, 41, 17))
        self.filas5.setChecked(True)
        self.filas5.setObjectName("filas5")
        self.ColumnasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ColumnasGroupBox.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.ColumnasGroupBox.setObjectName("ColumnasGroupBox")
        self.col2 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col2.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.col2.setChecked(False)
        self.col2.setObjectName("col2")
        self.col3 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col3.setGeometry(QtCore.QRect(50, 10, 31, 17))
        self.col3.setObjectName("col3")
        self.col4 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col4.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.col4.setObjectName("col4")
        self.col5 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col5.setGeometry(QtCore.QRect(130, 10, 41, 17))
        self.col5.setChecked(True)
        self.col5.setObjectName("col5")
        self.nuevaMatrizButt = QtWidgets.QPushButton(self.centralwidget)
        self.nuevaMatrizButt.setGeometry(QtCore.QRect(20, 440, 141, 23))
        self.nuevaMatrizButt.setObjectName("nuevaMatrizButt")
        self.sResutadosButt = QtWidgets.QPushButton(self.centralwidget)
        self.sResutadosButt.setGeometry(QtCore.QRect(20, 480, 141, 23))
        self.sResutadosButt.setObjectName("sResutadosButt")
        self.FIL1COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL1.setGeometry(QtCore.QRect(210, 10, 51, 91))
        self.FIL1COL1.setObjectName("FIL1COL1")
        self.DEMF1C1 = QtWidgets.QLineEdit(self.FIL1COL1)
        self.DEMF1C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C1.setObjectName("DEMF1C1")
        self.line = QtWidgets.QFrame(self.FIL1COL1)
        self.line.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.NUMF1C1 = QtWidgets.QLineEdit(self.FIL1COL1)
        self.NUMF1C1.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF1C1.setObjectName("NUMF1C1")
        self.DEMF1C1.raise_()
        self.NUMF1C1.raise_()
        self.line.raise_()
        self.DEMF1C1.raise_()
        self.line.raise_()
        self.NUMF1C1.raise_()
        self.FIL1COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL2.setGeometry(QtCore.QRect(270, 10, 51, 91))
        self.FIL1COL2.setObjectName("FIL1COL2")
        self.DEMF1C2 = QtWidgets.QLineEdit(self.FIL1COL2)
        self.DEMF1C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C2.setObjectName("DEMF1C2")
        self.line_12 = QtWidgets.QFrame(self.FIL1COL2)
        self.line_12.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.NUMF1C2 = QtWidgets.QLineEdit(self.FIL1COL2)
        self.NUMF1C2.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF1C2.setObjectName("NUMF1C2")
        self.FIL1COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL3.setGeometry(QtCore.QRect(330, 10, 51, 91))
        self.FIL1COL3.setObjectName("FIL1COL3")
        self.DEMF1C3 = QtWidgets.QLineEdit(self.FIL1COL3)
        self.DEMF1C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C3.setObjectName("DEMF1C3")
        self.line_13 = QtWidgets.QFrame(self.FIL1COL3)
        self.line_13.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.NUMF1C3 = QtWidgets.QLineEdit(self.FIL1COL3)
        self.NUMF1C3.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF1C3.setObjectName("NUMF1C3")
        self.FIL1COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL4.setGeometry(QtCore.QRect(390, 10, 51, 91))
        self.FIL1COL4.setObjectName("FIL1COL4")
        self.DEMF1C4 = QtWidgets.QLineEdit(self.FIL1COL4)
        self.DEMF1C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C4.setObjectName("DEMF1C4")
        self.line_14 = QtWidgets.QFrame(self.FIL1COL4)
        self.line_14.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.NUMF1C4 = QtWidgets.QLineEdit(self.FIL1COL4)
        self.NUMF1C4.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF1C4.setObjectName("NUMF1C4")
        self.FIL1COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL5.setGeometry(QtCore.QRect(450, 10, 51, 91))
        self.FIL1COL5.setObjectName("FIL1COL5")
        self.DEMF1C5 = QtWidgets.QLineEdit(self.FIL1COL5)
        self.DEMF1C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C5.setObjectName("DEMF1C5")
        self.line_15 = QtWidgets.QFrame(self.FIL1COL5)
        self.line_15.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.NUMF1C5 = QtWidgets.QLineEdit(self.FIL1COL5)
        self.NUMF1C5.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF1C5.setObjectName("NUMF1C5")
        self.FIL2COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL1.setGeometry(QtCore.QRect(210, 110, 51, 91))
        self.FIL2COL1.setObjectName("FIL2COL1")
        self.DEMF2C1 = QtWidgets.QLineEdit(self.FIL2COL1)
        self.DEMF2C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C1.setObjectName("DEMF2C1")
        self.line_16 = QtWidgets.QFrame(self.FIL2COL1)
        self.line_16.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.NUMF2C1 = QtWidgets.QLineEdit(self.FIL2COL1)
        self.NUMF2C1.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF2C1.setObjectName("NUMF2C1")
        self.FIL2COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL2.setGeometry(QtCore.QRect(270, 110, 51, 91))
        self.FIL2COL2.setObjectName("FIL2COL2")
        self.DEMF2C2 = QtWidgets.QLineEdit(self.FIL2COL2)
        self.DEMF2C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C2.setObjectName("DEMF2C2")
        self.line_17 = QtWidgets.QFrame(self.FIL2COL2)
        self.line_17.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.NUMF2C2 = QtWidgets.QLineEdit(self.FIL2COL2)
        self.NUMF2C2.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF2C2.setObjectName("NUMF2C2")
        self.FIL2COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL3.setGeometry(QtCore.QRect(330, 110, 51, 91))
        self.FIL2COL3.setObjectName("FIL2COL3")
        self.DEMF2C3 = QtWidgets.QLineEdit(self.FIL2COL3)
        self.DEMF2C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C3.setObjectName("DEMF2C3")
        self.line_18 = QtWidgets.QFrame(self.FIL2COL3)
        self.line_18.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.NUMF2C3 = QtWidgets.QLineEdit(self.FIL2COL3)
        self.NUMF2C3.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF2C3.setObjectName("NUMF2C3")
        self.FIL2COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL4.setGeometry(QtCore.QRect(390, 110, 51, 91))
        self.FIL2COL4.setObjectName("FIL2COL4")
        self.DEMF2C4 = QtWidgets.QLineEdit(self.FIL2COL4)
        self.DEMF2C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C4.setObjectName("DEMF2C4")
        self.line_19 = QtWidgets.QFrame(self.FIL2COL4)
        self.line_19.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.NUMF2C4 = QtWidgets.QLineEdit(self.FIL2COL4)
        self.NUMF2C4.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF2C4.setObjectName("NUMF2C4")
        self.FIL2COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL5.setGeometry(QtCore.QRect(450, 110, 51, 91))
        self.FIL2COL5.setObjectName("FIL2COL5")
        self.DEMF2C5 = QtWidgets.QLineEdit(self.FIL2COL5)
        self.DEMF2C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C5.setObjectName("DEMF2C5")
        self.line_20 = QtWidgets.QFrame(self.FIL2COL5)
        self.line_20.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.NUMF2C5 = QtWidgets.QLineEdit(self.FIL2COL5)
        self.NUMF2C5.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF2C5.setObjectName("NUMF2C5")
        self.FIL3COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL1.setGeometry(QtCore.QRect(210, 210, 51, 91))
        self.FIL3COL1.setObjectName("FIL3COL1")
        self.DEMF3C1 = QtWidgets.QLineEdit(self.FIL3COL1)
        self.DEMF3C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C1.setObjectName("DEMF3C1")
        self.line_21 = QtWidgets.QFrame(self.FIL3COL1)
        self.line_21.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.NUMF3C1 = QtWidgets.QLineEdit(self.FIL3COL1)
        self.NUMF3C1.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF3C1.setObjectName("NUMF3C1")
        self.FIL3COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL2.setGeometry(QtCore.QRect(270, 210, 51, 91))
        self.FIL3COL2.setObjectName("FIL3COL2")
        self.DEMF3C2 = QtWidgets.QLineEdit(self.FIL3COL2)
        self.DEMF3C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C2.setObjectName("DEMF3C2")
        self.line_22 = QtWidgets.QFrame(self.FIL3COL2)
        self.line_22.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.NUMF3C2 = QtWidgets.QLineEdit(self.FIL3COL2)
        self.NUMF3C2.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF3C2.setObjectName("NUMF3C2")
        self.FIL3COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL3.setGeometry(QtCore.QRect(330, 210, 51, 91))
        self.FIL3COL3.setObjectName("FIL3COL3")
        self.DEMF3C3 = QtWidgets.QLineEdit(self.FIL3COL3)
        self.DEMF3C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C3.setObjectName("DEMF3C3")
        self.line_23 = QtWidgets.QFrame(self.FIL3COL3)
        self.line_23.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.NUMF3C3 = QtWidgets.QLineEdit(self.FIL3COL3)
        self.NUMF3C3.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF3C3.setObjectName("NUMF3C3")
        self.FIL3COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL4.setGeometry(QtCore.QRect(390, 210, 51, 91))
        self.FIL3COL4.setObjectName("FIL3COL4")
        self.DEMF3C4 = QtWidgets.QLineEdit(self.FIL3COL4)
        self.DEMF3C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C4.setObjectName("DEMF3C4")
        self.line_24 = QtWidgets.QFrame(self.FIL3COL4)
        self.line_24.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.NUMF3C4 = QtWidgets.QLineEdit(self.FIL3COL4)
        self.NUMF3C4.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF3C4.setObjectName("NUMF3C4")
        self.FIL3COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL5.setGeometry(QtCore.QRect(450, 210, 51, 91))
        self.FIL3COL5.setObjectName("FIL3COL5")
        self.DEMF3C5 = QtWidgets.QLineEdit(self.FIL3COL5)
        self.DEMF3C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C5.setObjectName("DEMF3C5")
        self.line_25 = QtWidgets.QFrame(self.FIL3COL5)
        self.line_25.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.NUMF3C5 = QtWidgets.QLineEdit(self.FIL3COL5)
        self.NUMF3C5.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF3C5.setObjectName("NUMF3C5")
        self.FIL4COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL1.setGeometry(QtCore.QRect(210, 310, 51, 91))
        self.FIL4COL1.setObjectName("FIL4COL1")
        self.DEMF4C1 = QtWidgets.QLineEdit(self.FIL4COL1)
        self.DEMF4C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C1.setObjectName("DEMF4C1")
        self.line_26 = QtWidgets.QFrame(self.FIL4COL1)
        self.line_26.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.NUMF4C1 = QtWidgets.QLineEdit(self.FIL4COL1)
        self.NUMF4C1.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF4C1.setObjectName("NUMF4C1")
        self.FIL4COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL2.setGeometry(QtCore.QRect(270, 310, 51, 91))
        self.FIL4COL2.setObjectName("FIL4COL2")
        self.DEMF4C2 = QtWidgets.QLineEdit(self.FIL4COL2)
        self.DEMF4C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C2.setObjectName("DEMF4C2")
        self.line_27 = QtWidgets.QFrame(self.FIL4COL2)
        self.line_27.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.NUMF4C2 = QtWidgets.QLineEdit(self.FIL4COL2)
        self.NUMF4C2.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF4C2.setObjectName("NUMF4C2")
        self.FIL4COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL3.setGeometry(QtCore.QRect(330, 310, 51, 91))
        self.FIL4COL3.setObjectName("FIL4COL3")
        self.DEMF4C3 = QtWidgets.QLineEdit(self.FIL4COL3)
        self.DEMF4C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C3.setObjectName("DEMF4C3")
        self.line_28 = QtWidgets.QFrame(self.FIL4COL3)
        self.line_28.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.NUMF4C3 = QtWidgets.QLineEdit(self.FIL4COL3)
        self.NUMF4C3.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF4C3.setObjectName("NUMF4C3")
        self.FIL4COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL4.setGeometry(QtCore.QRect(390, 310, 51, 91))
        self.FIL4COL4.setObjectName("FIL4COL4")
        self.DEMF4C4 = QtWidgets.QLineEdit(self.FIL4COL4)
        self.DEMF4C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C4.setObjectName("DEMF4C4")
        self.line_29 = QtWidgets.QFrame(self.FIL4COL4)
        self.line_29.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.NUMF4C4 = QtWidgets.QLineEdit(self.FIL4COL4)
        self.NUMF4C4.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF4C4.setObjectName("NUMF4C4")
        self.FIL4COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL5.setGeometry(QtCore.QRect(450, 310, 51, 91))
        self.FIL4COL5.setObjectName("FIL4COL5")
        self.DEMF4C5 = QtWidgets.QLineEdit(self.FIL4COL5)
        self.DEMF4C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C5.setObjectName("DEMF4C5")
        self.line_30 = QtWidgets.QFrame(self.FIL4COL5)
        self.line_30.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.NUMF4C5 = QtWidgets.QLineEdit(self.FIL4COL5)
        self.NUMF4C5.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF4C5.setObjectName("NUMF4C5")
        self.FIL5COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL1.setGeometry(QtCore.QRect(210, 410, 51, 91))
        self.FIL5COL1.setObjectName("FIL5COL1")
        self.DEMF5C1 = QtWidgets.QLineEdit(self.FIL5COL1)
        self.DEMF5C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C1.setObjectName("DEMF5C1")
        self.line_31 = QtWidgets.QFrame(self.FIL5COL1)
        self.line_31.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.NUMF5C1 = QtWidgets.QLineEdit(self.FIL5COL1)
        self.NUMF5C1.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF5C1.setObjectName("NUMF5C1")
        self.FIL5COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL2.setGeometry(QtCore.QRect(270, 410, 51, 91))
        self.FIL5COL2.setObjectName("FIL5COL2")
        self.DEMF5C2 = QtWidgets.QLineEdit(self.FIL5COL2)
        self.DEMF5C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C2.setObjectName("DEMF5C2")
        self.line_32 = QtWidgets.QFrame(self.FIL5COL2)
        self.line_32.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.NUMF5C2 = QtWidgets.QLineEdit(self.FIL5COL2)
        self.NUMF5C2.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF5C2.setObjectName("NUMF5C2")
        self.FIL5COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL3.setGeometry(QtCore.QRect(330, 410, 51, 91))
        self.FIL5COL3.setObjectName("FIL5COL3")
        self.DEMF5C3 = QtWidgets.QLineEdit(self.FIL5COL3)
        self.DEMF5C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C3.setObjectName("DEMF5C3")
        self.line_33 = QtWidgets.QFrame(self.FIL5COL3)
        self.line_33.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.NUMF5C3 = QtWidgets.QLineEdit(self.FIL5COL3)
        self.NUMF5C3.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF5C3.setObjectName("NUMF5C3")
        self.FIL5COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL4.setGeometry(QtCore.QRect(390, 410, 51, 91))
        self.FIL5COL4.setObjectName("FIL5COL4")
        self.DEMF5C4 = QtWidgets.QLineEdit(self.FIL5COL4)
        self.DEMF5C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C4.setObjectName("DEMF5C4")
        self.line_34 = QtWidgets.QFrame(self.FIL5COL4)
        self.line_34.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.NUMF5C4 = QtWidgets.QLineEdit(self.FIL5COL4)
        self.NUMF5C4.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF5C4.setObjectName("NUMF5C4")
        self.FIL5COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL5.setEnabled(True)
        self.FIL5COL5.setGeometry(QtCore.QRect(450, 410, 51, 91))
        self.FIL5COL5.setObjectName("FIL5COL5")
        self.DEMF5C5 = QtWidgets.QLineEdit(self.FIL5COL5)
        self.DEMF5C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C5.setObjectName("DEMF5C5")
        self.line_35 = QtWidgets.QFrame(self.FIL5COL5)
        self.line_35.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.NUMF5C5 = QtWidgets.QLineEdit(self.FIL5COL5)
        self.NUMF5C5.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.NUMF5C5.setObjectName("NUMF5C5")
        self.OperacionesElementalesGrupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.OperacionesElementalesGrupBox.setGeometry(QtCore.QRect(10, 90, 181, 331))
        self.OperacionesElementalesGrupBox.setObjectName("OperacionesElementalesGrupBox")
        self.FilaxfilasGroupBox = QtWidgets.QGroupBox(self.OperacionesElementalesGrupBox)
        self.FilaxfilasGroupBox.setGeometry(QtCore.QRect(10, 20, 161, 81))
        self.FilaxfilasGroupBox.setObjectName("FilaxfilasGroupBox")
        self.filaA1 = QtWidgets.QLineEdit(self.FilaxfilasGroupBox)
        self.filaA1.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.filaA1.setObjectName("filaA1")
        self.filaA2 = QtWidgets.QLineEdit(self.FilaxfilasGroupBox)
        self.filaA2.setGeometry(QtCore.QRect(110, 20, 41, 20))
        self.filaA2.setObjectName("filaA2")
        self.RealizarTipoA = QtWidgets.QPushButton(self.FilaxfilasGroupBox)
        self.RealizarTipoA.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.RealizarTipoA.setObjectName("RealizarTipoA")
        self.label = QtWidgets.QLabel(self.FilaxfilasGroupBox)
        self.label.setGeometry(QtCore.QRect(60, 20, 41, 16))
        self.label.setObjectName("label")
        self.groupBox_27 = QtWidgets.QGroupBox(self.OperacionesElementalesGrupBox)
        self.groupBox_27.setGeometry(QtCore.QRect(10, 110, 161, 101))
        self.groupBox_27.setObjectName("groupBox_27")
        self.label_2 = QtWidgets.QLabel(self.groupBox_27)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_2.setObjectName("label_2")
        self.filaB = QtWidgets.QLineEdit(self.groupBox_27)
        self.filaB.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.filaB.setObjectName("filaB")
        self.label_3 = QtWidgets.QLabel(self.groupBox_27)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.constanteB = QtWidgets.QLineEdit(self.groupBox_27)
        self.constanteB.setGeometry(QtCore.QRect(60, 40, 21, 20))
        self.constanteB.setObjectName("constanteB")
        self.label_4 = QtWidgets.QLabel(self.groupBox_27)
        self.label_4.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.label_4.setObjectName("label_4")
        self.RealizarTipoB = QtWidgets.QPushButton(self.groupBox_27)
        self.RealizarTipoB.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.RealizarTipoB.setObjectName("RealizarTipoB")
        self.groupBox_28 = QtWidgets.QGroupBox(self.OperacionesElementalesGrupBox)
        self.groupBox_28.setGeometry(QtCore.QRect(10, 220, 161, 101))
        self.groupBox_28.setObjectName("groupBox_28")
        self.label_5 = QtWidgets.QLabel(self.groupBox_28)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_28)
        self.label_6.setGeometry(QtCore.QRect(130, 20, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_28)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_28)
        self.label_8.setGeometry(QtCore.QRect(100, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_28)
        self.label_9.setGeometry(QtCore.QRect(40, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        #
        self.label_10 = QtWidgets.QLabel(self.groupBox_28)
        self.label_10.setGeometry(QtCore.QRect(42, 50, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        #
        self.filaC1 = QtWidgets.QLineEdit(self.groupBox_28)
        self.filaC1.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.filaC1.setObjectName("filaC1")
        self.constanteC = QtWidgets.QLineEdit(self.groupBox_28)
        self.constanteC.setGeometry(QtCore.QRect(70, 40, 21, 20))
        self.constanteC.setObjectName("constanteC")
        self.filaC2 = QtWidgets.QLineEdit(self.groupBox_28)
        self.filaC2.setGeometry(QtCore.QRect(130, 40, 21, 20))
        self.filaC2.setObjectName("filaC2")
        self.RealizarTipoC = QtWidgets.QPushButton(self.groupBox_28)
        self.RealizarTipoC.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.RealizarTipoC.setObjectName("RealizarTipoC")
        TareaAlgebra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TareaAlgebra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 20))
        self.menubar.setObjectName("menubar")
        TareaAlgebra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TareaAlgebra)
        self.statusbar.setObjectName("statusbar")
        self.sResutadosButt.setEnabled(False)
        self.RealizarTipoA.setEnabled(False)
        self.RealizarTipoB.setEnabled(False)
        self.RealizarTipoC.setEnabled(False)
        TareaAlgebra.setStatusBar(self.statusbar)
        self.retranslateUi(TareaAlgebra)
        QtCore.QMetaObject.connectSlotsByName(TareaAlgebra)
        self.home()

    def retranslateUi(self, TareaAlgebra):
        _translate = QtCore.QCoreApplication.translate
        TareaAlgebra.setWindowTitle(_translate("TareaAlgebra", "Tarea Programada Parte1"))
        self.FilasGroupBox.setTitle(_translate("TareaAlgebra", "Filas"))
        self.filas2.setText(_translate("TareaAlgebra", "2"))
        self.filas3.setText(_translate("TareaAlgebra", "3"))
        self.filas4.setText(_translate("TareaAlgebra", "4"))
        self.filas5.setText(_translate("TareaAlgebra", "5"))
        self.ColumnasGroupBox.setTitle(_translate("TareaAlgebra", "Columnas"))
        self.col2.setText(_translate("TareaAlgebra", "2"))
        self.col3.setText(_translate("TareaAlgebra", "3"))
        self.col4.setText(_translate("TareaAlgebra", "4"))
        self.col5.setText(_translate("TareaAlgebra", "5"))
        self.nuevaMatrizButt.setText(_translate("TareaAlgebra", "Crear Matriz"))
        self.sResutadosButt.setText(_translate("TareaAlgebra", "Secuencia de Resultados"))
        self.FIL1COL1.setTitle(_translate("TareaAlgebra", "FIL1COL1"))
        self.DEMF1C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C1.setText(_translate("TareaAlgebra", "0"))
        self.FIL1COL2.setTitle(_translate("TareaAlgebra", "FIL1COL2"))
        self.DEMF1C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C2.setText(_translate("TareaAlgebra", "0"))
        self.FIL1COL3.setTitle(_translate("TareaAlgebra", "FIL1COL3"))
        self.DEMF1C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C3.setText(_translate("TareaAlgebra", "0"))
        self.FIL1COL4.setTitle(_translate("TareaAlgebra", "FIL1COL4"))
        self.DEMF1C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C4.setText(_translate("TareaAlgebra", "0"))
        self.FIL1COL5.setTitle(_translate("TareaAlgebra", "FIL1COL5"))
        self.DEMF1C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C5.setText(_translate("TareaAlgebra", "0"))
        self.FIL2COL1.setTitle(_translate("TareaAlgebra", "FIL2COL1"))
        self.DEMF2C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C1.setText(_translate("TareaAlgebra", "0"))
        self.FIL2COL2.setTitle(_translate("TareaAlgebra", "FIL2COL2"))
        self.DEMF2C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C2.setText(_translate("TareaAlgebra", "0"))
        self.FIL2COL3.setTitle(_translate("TareaAlgebra", "FIL2COL3"))
        self.DEMF2C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C3.setText(_translate("TareaAlgebra", "0"))
        self.FIL2COL4.setTitle(_translate("TareaAlgebra", "FIL2COL4"))
        self.DEMF2C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C4.setText(_translate("TareaAlgebra", "0"))
        self.FIL2COL5.setTitle(_translate("TareaAlgebra", "FIL2COL5"))
        self.DEMF2C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C5.setText(_translate("TareaAlgebra", "0"))
        self.FIL3COL1.setTitle(_translate("TareaAlgebra", "FIL3COL1"))
        self.DEMF3C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C1.setText(_translate("TareaAlgebra", "0"))
        self.FIL3COL2.setTitle(_translate("TareaAlgebra", "FIL3COL2"))
        self.DEMF3C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C2.setText(_translate("TareaAlgebra", "0"))
        self.FIL3COL3.setTitle(_translate("TareaAlgebra", "FIL3COL3"))
        self.DEMF3C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C3.setText(_translate("TareaAlgebra", "0"))
        self.FIL3COL4.setTitle(_translate("TareaAlgebra", "FIL3COL4"))
        self.DEMF3C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C4.setText(_translate("TareaAlgebra", "0"))
        self.FIL3COL5.setTitle(_translate("TareaAlgebra", "FIL3COL5"))
        self.DEMF3C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C5.setText(_translate("TareaAlgebra", "0"))
        self.FIL4COL1.setTitle(_translate("TareaAlgebra", "FIL4COL1"))
        self.DEMF4C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C1.setText(_translate("TareaAlgebra", "0"))
        self.FIL4COL2.setTitle(_translate("TareaAlgebra", "FIL4COL2"))
        self.DEMF4C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C2.setText(_translate("TareaAlgebra", "0"))
        self.FIL4COL3.setTitle(_translate("TareaAlgebra", "FIL4COL3"))
        self.DEMF4C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C3.setText(_translate("TareaAlgebra", "0"))
        self.FIL4COL4.setTitle(_translate("TareaAlgebra", "FIL4COL4"))
        self.DEMF4C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C4.setText(_translate("TareaAlgebra", "0"))
        self.FIL4COL5.setTitle(_translate("TareaAlgebra", "FIL4COL5"))
        self.DEMF4C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C5.setText(_translate("TareaAlgebra", "0"))
        self.FIL5COL1.setTitle(_translate("TareaAlgebra", "FIL5COL1"))
        self.DEMF5C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C1.setText(_translate("TareaAlgebra", "0"))
        self.FIL5COL2.setTitle(_translate("TareaAlgebra", "FIL5COL2"))
        self.DEMF5C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C2.setText(_translate("TareaAlgebra", "0"))
        self.FIL5COL3.setTitle(_translate("TareaAlgebra", "FIL5COL3"))
        self.DEMF5C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C3.setText(_translate("TareaAlgebra", "0"))
        self.FIL5COL4.setTitle(_translate("TareaAlgebra", "FIL5COL4"))
        self.DEMF5C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C4.setText(_translate("TareaAlgebra", "0"))
        self.FIL5COL5.setTitle(_translate("TareaAlgebra", "FIL5COL5"))
        self.DEMF5C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C5.setText(_translate("TareaAlgebra", "0"))
        self.OperacionesElementalesGrupBox.setTitle(_translate("TareaAlgebra", "Operaciones Elementales"))
        self.FilaxfilasGroupBox.setTitle(_translate("TareaAlgebra", "Cambiar fila por fila"))
        self.RealizarTipoA.setText(_translate("TareaAlgebra", "Realizar"))
        self.label.setText(_translate("TareaAlgebra", "<----->"))
        self.groupBox_27.setTitle(_translate("TareaAlgebra", "Fila por Constante"))
        self.label_2.setText(_translate("TareaAlgebra", "Fila"))
        self.label_3.setText(_translate("TareaAlgebra", "*"))
        self.label_4.setText(_translate("TareaAlgebra", "Constante"))
        self.RealizarTipoB.setText(_translate("TareaAlgebra", "Realizar"))
        self.groupBox_28.setTitle(_translate("TareaAlgebra", "Tipo C"))
        self.label_5.setText(_translate("TareaAlgebra", "Fila"))
        self.label_6.setText(_translate("TareaAlgebra", "Fila"))
        self.label_7.setText(_translate("TareaAlgebra", "Constante"))
        self.label_8.setText(_translate("TareaAlgebra", "*"))
        self.label_9.setText(_translate("TareaAlgebra", "+"))
        self.label_10.setText(_translate("TareaAlgebra", "-"))
        self.RealizarTipoC.setText(_translate("TareaAlgebra", "Realizar"))


    def resetMatriz(self):
        for fila in self.matrizEnInterfaz:
            for columna in fila:
                columna.setEnabled(True)

    def setEnableMatriz(self):
        self.resetMatriz()
        matriz = self.matrizEnInterfaz
        numCol = 5
        numFil = 5
        if (self.col2.isChecked()):
            numCol = 2
        elif (self.col3.isChecked()):
            numCol = 3
        elif (self.col4.isChecked()):
            numCol = 4
        else:
            pass
        if (self.filas2.isChecked()):
            numFil = 2
        elif (self.filas3.isChecked()):
            numFil = 3
        elif (self.filas4.isChecked()):
            numFil = 4
        else:
            pass
        self.filas = numFil
        self.columnas = numCol
        while (numFil < 5):
            for i in range(0, 5):
                matriz[numFil][i].setEnabled(False)
            numFil += 1
        for i in range(0, 5):
            tmp = numCol
            while (tmp < 5):
                matriz[i][tmp].setEnabled(False)
                tmp+=1
        #self.nuevaMatrizButt.setEnabled(False)
        self.nuevaMatrizButt.setText("Nueva Matriz")
        self.RealizarTipoA.setEnabled(True)
        self.RealizarTipoB.setEnabled(True)
        self.RealizarTipoC.setEnabled(True)
        #self.FilasGroupBox.setEnabled(False)
        #self.ColumnasGroupBox.setEnabled(False)
        self.setMatrizActiva()

    def setMatrizActiva(self):
        for i in range(0, self.filas):
            self.matrizActiva.insert(i,[])
            self.matrizReal.insert(i,[])
            for j in range(0, self.columnas):
                self.matrizActiva[i].insert(j, self.matrizEnInterfaz[i][j])

    def generarMatrizReal(self):
        self.matrizReal = []
        for i in range(0, self.filas):
            self.matrizReal.insert(i,[])
        for i in range(0,self.filas):
            for j in range(0,self.columnas):
                tmp = self.matrizActiva[i][j].children()
                print(int(tmp[2].text()),int(tmp[0].text()))
                self.matrizReal[i].insert(j, Fraction(int(tmp[2].text()),int(tmp[0].text())))

    def actualizarMatrizUI(self,matriz):
        for i in range(0,self.filas):
            for j in range(0,self.columnas):
                tmp = self.matrizActiva[i][j].children()
                num = Fraction(matriz[i][j])
                tmp[2].setText(str(num.numerator))
                tmp[0].setText(str(num.denominator))



    def tipoA(self):
        self.generarMatrizReal()
        filaCambio1 = int(self.filaA1.text())
        filaCambio2 = int(self.filaA2.text())
        self.matrizReal = intercambiarFilas(self.matrizReal, filaCambio1, filaCambio2)
        self.actualizarMatrizUI(self.matrizReal)





    def home(self):
        self.FIL1COL1.children()
        self.matrizEnInterfaz = [[self.FIL1COL1,self.FIL1COL2,self.FIL1COL3,self.FIL1COL4,self.FIL1COL5],
                            [self.FIL2COL1,self.FIL2COL2,self.FIL2COL3,self.FIL2COL4,self.FIL2COL5],
                            [self.FIL3COL1,self.FIL3COL2,self.FIL3COL3,self.FIL3COL4,self.FIL3COL5],
                            [self.FIL4COL1,self.FIL4COL2,self.FIL4COL3,self.FIL4COL4,self.FIL4COL5],
                            [self.FIL5COL1,self.FIL5COL2,self.FIL5COL3,self.FIL5COL4,self.FIL5COL5]]
        self.nuevaMatrizButt.clicked.connect(self.setEnableMatriz)
        self.RealizarTipoA.clicked.connect(self.tipoA)
        self.RealizarTipoB.clicked.connect(self.setEnableMatriz)
        self.RealizarTipoC.clicked.connect(self.setEnableMatriz)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TareaAlgebra = QtWidgets.QMainWindow()
    ui = Ui_TareaAlgebra()
    ui.setupUi(TareaAlgebra)
    TareaAlgebra.show()
    sys.exit(app.exec_())

