# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alvar_000\Documents\registro\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Interfaz import Ui_TareaAlgebra

filas = 5
columnas = 5

class Ui_Dialog(object):
    matrizEnInterfaz = []
    matrizActiva = []
    matrizReal = []


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 531)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 310, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(320, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(120, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 240, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 380, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(220, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.siguienteBtn = QtWidgets.QPushButton(Dialog)
        self.siguienteBtn.setGeometry(QtCore.QRect(300, 480, 75, 23))
        self.siguienteBtn.setObjectName("siguienteBtn")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(270, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(100, 60, 271, 371))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.FIL2COL3 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL2COL3.setGeometry(QtCore.QRect(110, 80, 51, 71))
        self.FIL2COL3.setTitle("")
        self.FIL2COL3.setObjectName("FIL2COL3")
        self.DEMF2C3 = QtWidgets.QLineEdit(self.FIL2COL3)
        self.DEMF2C3.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF2C3.setObjectName("DEMF2C3")
        self.line_25 = QtWidgets.QFrame(self.FIL2COL3)
        self.line_25.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.NUMF2C3 = QtWidgets.QLineEdit(self.FIL2COL3)
        self.NUMF2C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C3.setObjectName("NUMF2C3")
        self.FIL3COL1 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL3COL1.setGeometry(QtCore.QRect(10, 150, 51, 71))
        self.FIL3COL1.setTitle("")
        self.FIL3COL1.setObjectName("FIL3COL1")
        self.DEMF3C1 = QtWidgets.QLineEdit(self.FIL3COL1)
        self.DEMF3C1.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF3C1.setObjectName("DEMF3C1")
        self.line_9 = QtWidgets.QFrame(self.FIL3COL1)
        self.line_9.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.NUMF3C1 = QtWidgets.QLineEdit(self.FIL3COL1)
        self.NUMF3C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C1.setObjectName("NUMF3C1")
        self.FIL3COL3 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL3COL3.setGeometry(QtCore.QRect(110, 150, 51, 71))
        self.FIL3COL3.setTitle("")
        self.FIL3COL3.setObjectName("FIL3COL3")
        self.DEMF3C3 = QtWidgets.QLineEdit(self.FIL3COL3)
        self.DEMF3C3.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF3C3.setObjectName("DEMF3C3")
        self.line_51 = QtWidgets.QFrame(self.FIL3COL3)
        self.line_51.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_51.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.NUMF3C3 = QtWidgets.QLineEdit(self.FIL3COL3)
        self.NUMF3C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C3.setObjectName("NUMF3C3")
        self.FIL3COL2 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL3COL2.setGeometry(QtCore.QRect(60, 150, 51, 71))
        self.FIL3COL2.setTitle("")
        self.FIL3COL2.setObjectName("FIL3COL2")
        self.DEMF3C2 = QtWidgets.QLineEdit(self.FIL3COL2)
        self.DEMF3C2.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF3C2.setObjectName("DEMF3C2")
        self.line_41 = QtWidgets.QFrame(self.FIL3COL2)
        self.line_41.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.NUMF3C2 = QtWidgets.QLineEdit(self.FIL3COL2)
        self.NUMF3C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C2.setObjectName("NUMF3C2")
        self.FIL1COL1 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL1COL1.setGeometry(QtCore.QRect(10, 10, 51, 71))
        self.FIL1COL1.setTitle("")
        self.FIL1COL1.setObjectName("FIL1COL1")
        self.DEMF1C1 = QtWidgets.QLineEdit(self.FIL1COL1)
        self.DEMF1C1.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF1C1.setObjectName("DEMF1C1")
        self.line = QtWidgets.QFrame(self.FIL1COL1)
        self.line.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.NUMF1C1 = QtWidgets.QLineEdit(self.FIL1COL1)
        self.NUMF1C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C1.setObjectName("NUMF1C1")
        self.FIL2COL2 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL2COL2.setGeometry(QtCore.QRect(60, 80, 51, 71))
        self.FIL2COL2.setTitle("")
        self.FIL2COL2.setObjectName("FIL2COL2")
        self.DEMF2C2 = QtWidgets.QLineEdit(self.FIL2COL2)
        self.DEMF2C2.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF2C2.setObjectName("DEMF2C2")
        self.line_28 = QtWidgets.QFrame(self.FIL2COL2)
        self.line_28.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.NUMF2C2 = QtWidgets.QLineEdit(self.FIL2COL2)
        self.NUMF2C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C2.setObjectName("NUMF2C2")
        self.FIL1COL2 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL1COL2.setGeometry(QtCore.QRect(60, 10, 51, 71))
        self.FIL1COL2.setTitle("")
        self.FIL1COL2.setObjectName("FIL1COL2")
        self.DEMF1C2 = QtWidgets.QLineEdit(self.FIL1COL2)
        self.DEMF1C2.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF1C2.setObjectName("DEMF1C2")
        self.line_12 = QtWidgets.QFrame(self.FIL1COL2)
        self.line_12.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.NUMF1C2 = QtWidgets.QLineEdit(self.FIL1COL2)
        self.NUMF1C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C2.setObjectName("NUMF1C2")
        self.FIL4COL5 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL4COL5.setGeometry(QtCore.QRect(210, 220, 51, 71))
        self.FIL4COL5.setTitle("")
        self.FIL4COL5.setObjectName("FIL4COL5")
        self.DEMF4C5 = QtWidgets.QLineEdit(self.FIL4COL5)
        self.DEMF4C5.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF4C5.setObjectName("DEMF4C5")
        self.line_42 = QtWidgets.QFrame(self.FIL4COL5)
        self.line_42.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.NUMF4C5 = QtWidgets.QLineEdit(self.FIL4COL5)
        self.NUMF4C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C5.setObjectName("NUMF4C5")
        self.FIL2COL4 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL2COL4.setGeometry(QtCore.QRect(160, 80, 51, 71))
        self.FIL2COL4.setTitle("")
        self.FIL2COL4.setObjectName("FIL2COL4")
        self.DEMF2C4 = QtWidgets.QLineEdit(self.FIL2COL4)
        self.DEMF2C4.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF2C4.setObjectName("DEMF2C4")
        self.line_27 = QtWidgets.QFrame(self.FIL2COL4)
        self.line_27.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.NUMF2C4 = QtWidgets.QLineEdit(self.FIL2COL4)
        self.NUMF2C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C4.setObjectName("NUMF2C4")
        self.FIL5COL2 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL5COL2.setGeometry(QtCore.QRect(60, 290, 51, 71))
        self.FIL5COL2.setTitle("")
        self.FIL5COL2.setObjectName("FIL5COL2")
        self.DEMF5C2 = QtWidgets.QLineEdit(self.FIL5COL2)
        self.DEMF5C2.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF5C2.setObjectName("DEMF5C2")
        self.line_54 = QtWidgets.QFrame(self.FIL5COL2)
        self.line_54.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_54.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.NUMF5C2 = QtWidgets.QLineEdit(self.FIL5COL2)
        self.NUMF5C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C2.setObjectName("NUMF5C2")
        self.FIL3COL4 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL3COL4.setGeometry(QtCore.QRect(160, 150, 51, 71))
        self.FIL3COL4.setTitle("")
        self.FIL3COL4.setObjectName("FIL3COL4")
        self.DEMF3C4 = QtWidgets.QLineEdit(self.FIL3COL4)
        self.DEMF3C4.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF3C4.setObjectName("DEMF3C4")
        self.line_43 = QtWidgets.QFrame(self.FIL3COL4)
        self.line_43.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.NUMF3C4 = QtWidgets.QLineEdit(self.FIL3COL4)
        self.NUMF3C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C4.setObjectName("NUMF3C4")
        self.FIL1COL5 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL1COL5.setGeometry(QtCore.QRect(210, 10, 51, 71))
        self.FIL1COL5.setTitle("")
        self.FIL1COL5.setObjectName("FIL1COL5")
        self.DEMF1C5 = QtWidgets.QLineEdit(self.FIL1COL5)
        self.DEMF1C5.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF1C5.setObjectName("DEMF1C5")
        self.line_16 = QtWidgets.QFrame(self.FIL1COL5)
        self.line_16.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.NUMF1C5 = QtWidgets.QLineEdit(self.FIL1COL5)
        self.NUMF1C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C5.setObjectName("NUMF1C5")
        self.FIL4COL2 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL4COL2.setGeometry(QtCore.QRect(60, 220, 51, 71))
        self.FIL4COL2.setTitle("")
        self.FIL4COL2.setObjectName("FIL4COL2")
        self.DEMF4C2 = QtWidgets.QLineEdit(self.FIL4COL2)
        self.DEMF4C2.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF4C2.setObjectName("DEMF4C2")
        self.line_45 = QtWidgets.QFrame(self.FIL4COL2)
        self.line_45.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.NUMF4C2 = QtWidgets.QLineEdit(self.FIL4COL2)
        self.NUMF4C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C2.setObjectName("NUMF4C2")
        self.FIL5COL3 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL5COL3.setGeometry(QtCore.QRect(110, 290, 51, 71))
        self.FIL5COL3.setTitle("")
        self.FIL5COL3.setObjectName("FIL15COL3")
        self.DEMF5C3 = QtWidgets.QLineEdit(self.FIL5COL3)
        self.DEMF5C3.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF5C3.setObjectName("DEMF5C3")
        self.line_55 = QtWidgets.QFrame(self.FIL5COL3)
        self.line_55.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_55.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.NUMF5C3 = QtWidgets.QLineEdit(self.FIL5COL3)
        self.NUMF5C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C3.setObjectName("NUMF5C3")
        self.FIL4COL3 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL4COL3.setGeometry(QtCore.QRect(110, 220, 51, 71))
        self.FIL4COL3.setTitle("")
        self.FIL4COL3.setObjectName("FIL4COL3")
        self.DEMF4C3 = QtWidgets.QLineEdit(self.FIL4COL3)
        self.DEMF4C3.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF4C3.setObjectName("DEMF4C3")
        self.line_50 = QtWidgets.QFrame(self.FIL4COL3)
        self.line_50.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_50.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.NUMF4C3 = QtWidgets.QLineEdit(self.FIL4COL3)
        self.NUMF4C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C3.setObjectName("NUMF4C3")
        self.FIL5COL4 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL5COL4.setGeometry(QtCore.QRect(160, 290, 51, 71))
        self.FIL5COL4.setTitle("")
        self.FIL5COL4.setObjectName("FIL5COL4")
        self.DEMF5C4 = QtWidgets.QLineEdit(self.FIL5COL4)
        self.DEMF5C4.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF5C4.setObjectName("DEMF5C4")
        self.line_56 = QtWidgets.QFrame(self.FIL5COL4)
        self.line_56.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_56.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.NUMF5C4 = QtWidgets.QLineEdit(self.FIL5COL4)
        self.NUMF5C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C4.setObjectName("NUMF5C4")
        self.FIL4COL1 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL4COL1.setGeometry(QtCore.QRect(10, 220, 51, 71))
        self.FIL4COL1.setTitle("")
        self.FIL4COL1.setObjectName("FIL4COL1")
        self.DEMF4C1 = QtWidgets.QLineEdit(self.FIL4COL1)
        self.DEMF4C1.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF4C1.setObjectName("DEMF4C1")
        self.line_8 = QtWidgets.QFrame(self.FIL4COL1)
        self.line_8.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.NUMF4C1 = QtWidgets.QLineEdit(self.FIL4COL1)
        self.NUMF4C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C1.setObjectName("NUMF4C1")
        self.FIL4COL4 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL4COL4.setGeometry(QtCore.QRect(160, 220, 51, 71))
        self.FIL4COL4.setTitle("")
        self.FIL4COL4.setObjectName("FIL4COL4")
        self.DEMF4C4 = QtWidgets.QLineEdit(self.FIL4COL4)
        self.DEMF4C4.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF4C4.setObjectName("DEMF4C4")
        self.line_44 = QtWidgets.QFrame(self.FIL4COL4)
        self.line_44.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.NUMF4C4 = QtWidgets.QLineEdit(self.FIL4COL4)
        self.NUMF4C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C4.setObjectName("NUMF4C4")
        self.FIL1COL4 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL1COL4.setGeometry(QtCore.QRect(160, 10, 51, 71))
        self.FIL1COL4.setTitle("")
        self.FIL1COL4.setObjectName("FIL1COL4")
        self.DEMF1C4 = QtWidgets.QLineEdit(self.FIL1COL4)
        self.DEMF1C4.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF1C4.setObjectName("DEMF1C4")
        self.line_14 = QtWidgets.QFrame(self.FIL1COL4)
        self.line_14.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.NUMF1C4 = QtWidgets.QLineEdit(self.FIL1COL4)
        self.NUMF1C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C4.setObjectName("NUMF1C4")
        self.FIL3COL5 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL3COL5.setGeometry(QtCore.QRect(210, 150, 51, 71))
        self.FIL3COL5.setTitle("")
        self.FIL3COL5.setObjectName("FIL3COL5")
        self.DEMF3C5 = QtWidgets.QLineEdit(self.FIL3COL5)
        self.DEMF3C5.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF3C5.setObjectName("DEMF3C5")
        self.line_52 = QtWidgets.QFrame(self.FIL3COL5)
        self.line_52.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_52.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.NUMF3C5 = QtWidgets.QLineEdit(self.FIL3COL5)
        self.NUMF3C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C5.setObjectName("NUMF3C5")
        self.FIL2COL5 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL2COL5.setGeometry(QtCore.QRect(210, 80, 51, 71))
        self.FIL2COL5.setTitle("")
        self.FIL2COL5.setObjectName("FIL2COL5")
        self.DEMF2C5 = QtWidgets.QLineEdit(self.FIL2COL5)
        self.DEMF2C5.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF2C5.setObjectName("DEMF2C5")
        self.line_26 = QtWidgets.QFrame(self.FIL2COL5)
        self.line_26.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.NUMF2C5 = QtWidgets.QLineEdit(self.FIL2COL5)
        self.NUMF2C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C5.setObjectName("NUMF2C5")
        self.FIL2COL1 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL2COL1.setGeometry(QtCore.QRect(10, 80, 51, 71))
        self.FIL2COL1.setTitle("")
        self.FIL2COL1.setObjectName("FIL2COL1")
        self.DEMF2C1 = QtWidgets.QLineEdit(self.FIL2COL1)
        self.DEMF2C1.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF2C1.setObjectName("DEMF2C1")
        self.line_4 = QtWidgets.QFrame(self.FIL2COL1)
        self.line_4.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.NUMF2C1 = QtWidgets.QLineEdit(self.FIL2COL1)
        self.NUMF2C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C1.setObjectName("NUMF2C1")
        self.FIL1COL3 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL1COL3.setGeometry(QtCore.QRect(110, 10, 51, 71))
        self.FIL1COL3.setTitle("")
        self.FIL1COL3.setObjectName("FIL1COL3")
        self.DEMF1C3 = QtWidgets.QLineEdit(self.FIL1COL3)
        self.DEMF1C3.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF1C3.setObjectName("DEMF1C3")
        self.line_13 = QtWidgets.QFrame(self.FIL1COL3)
        self.line_13.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.NUMF1C3 = QtWidgets.QLineEdit(self.FIL1COL3)
        self.NUMF1C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C3.setObjectName("NUMF1C3")
        self.FIL5COL5 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL5COL5.setGeometry(QtCore.QRect(210, 290, 51, 71))
        self.FIL5COL5.setTitle("")
        self.FIL5COL5.setObjectName("FIL5COL5")
        self.DEMF5C5 = QtWidgets.QLineEdit(self.FIL5COL5)
        self.DEMF5C5.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF5C5.setObjectName("DEMF5C5")
        self.line_53 = QtWidgets.QFrame(self.FIL5COL5)
        self.line_53.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_53.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.NUMF5C5 = QtWidgets.QLineEdit(self.FIL5COL5)
        self.NUMF5C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C5.setObjectName("NUMF5C5")
        self.FIL5COL1 = QtWidgets.QGroupBox(self.groupBox)
        self.FIL5COL1.setGeometry(QtCore.QRect(10, 290, 51, 71))
        self.FIL5COL1.setTitle("")
        self.FIL5COL1.setObjectName("FIL5COL1")
        self.DEMF5C1 = QtWidgets.QLineEdit(self.FIL5COL1)
        self.DEMF5C1.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.DEMF5C1.setObjectName("DEMF5C1")
        self.line_11 = QtWidgets.QFrame(self.FIL5COL1)
        self.line_11.setGeometry(QtCore.QRect(10, 25, 31, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.NUMF5C1 = QtWidgets.QLineEdit(self.FIL5COL1)
        self.NUMF5C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C1.setObjectName("NUMF5C1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 100, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(170, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(190, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.anteriorBtn = QtWidgets.QPushButton(Dialog)
        self.anteriorBtn.setGeometry(QtCore.QRect(60, 480, 75, 23))
        self.anteriorBtn.setObjectName("anteriorBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Fila 4"))
        self.label_11.setText(_translate("Dialog", "C5"))
        self.label_7.setText(_translate("Dialog", "C1"))
        self.label_3.setText(_translate("Dialog", "Fila 3"))
        self.label_2.setText(_translate("Dialog", "Fila 2"))
        self.label_5.setText(_translate("Dialog", "Fila 5"))
        self.label_9.setText(_translate("Dialog", "C3"))
        self.siguienteBtn.setText(_translate("Dialog", "Siguiente"))
        self.label_10.setText(_translate("Dialog", "C4"))
        self.DEMF2C3.setText(_translate("Dialog", "1"))
        self.NUMF2C3.setText(_translate("Dialog", "0"))
        self.DEMF3C1.setText(_translate("Dialog", "1"))
        self.NUMF3C1.setText(_translate("Dialog", "0"))
        self.DEMF3C3.setText(_translate("Dialog", "1"))
        self.NUMF3C3.setText(_translate("Dialog", "0"))
        self.DEMF3C2.setText(_translate("Dialog", "1"))
        self.NUMF3C2.setText(_translate("Dialog", "0"))
        self.DEMF1C1.setText(_translate("Dialog", "1"))
        self.NUMF1C1.setText(_translate("Dialog", "0"))
        self.DEMF2C2.setText(_translate("Dialog", "1"))
        self.NUMF2C2.setText(_translate("Dialog", "0"))
        self.DEMF1C2.setText(_translate("Dialog", "1"))
        self.NUMF1C2.setText(_translate("Dialog", "0"))
        self.DEMF4C5.setText(_translate("Dialog", "1"))
        self.NUMF4C5.setText(_translate("Dialog", "0"))
        self.DEMF2C4.setText(_translate("Dialog", "1"))
        self.NUMF2C4.setText(_translate("Dialog", "0"))
        self.DEMF5C2.setText(_translate("Dialog", "1"))
        self.NUMF5C2.setText(_translate("Dialog", "0"))
        self.DEMF3C4.setText(_translate("Dialog", "1"))
        self.NUMF3C4.setText(_translate("Dialog", "0"))
        self.DEMF1C5.setText(_translate("Dialog", "1"))
        self.NUMF1C5.setText(_translate("Dialog", "0"))
        self.DEMF4C2.setText(_translate("Dialog", "1"))
        self.NUMF4C2.setText(_translate("Dialog", "0"))
        self.DEMF5C3.setText(_translate("Dialog", "1"))
        self.NUMF5C3.setText(_translate("Dialog", "0"))
        self.DEMF4C3.setText(_translate("Dialog", "1"))
        self.NUMF4C3.setText(_translate("Dialog", "0"))
        self.DEMF5C4.setText(_translate("Dialog", "1"))
        self.NUMF5C4.setText(_translate("Dialog", "0"))
        self.DEMF4C1.setText(_translate("Dialog", "1"))
        self.NUMF4C1.setText(_translate("Dialog", "0"))
        self.DEMF4C4.setText(_translate("Dialog", "1"))
        self.NUMF4C4.setText(_translate("Dialog", "0"))
        self.DEMF1C4.setText(_translate("Dialog", "1"))
        self.NUMF1C4.setText(_translate("Dialog", "0"))
        self.DEMF3C5.setText(_translate("Dialog", "1"))
        self.NUMF3C5.setText(_translate("Dialog", "0"))
        self.DEMF2C5.setText(_translate("Dialog", "1"))
        self.NUMF2C5.setText(_translate("Dialog", "0"))
        self.DEMF2C1.setText(_translate("Dialog", "1"))
        self.NUMF2C1.setText(_translate("Dialog", "0"))
        self.DEMF1C3.setText(_translate("Dialog", "1"))
        self.NUMF1C3.setText(_translate("Dialog", "0"))
        self.DEMF5C5.setText(_translate("Dialog", "1"))
        self.NUMF5C5.setText(_translate("Dialog", "0"))
        self.DEMF5C1.setText(_translate("Dialog", "1"))
        self.NUMF5C1.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Fila 1"))
        self.label_8.setText(_translate("Dialog", "C2"))
        self.label_6.setText(_translate("Dialog", "COLUMNAS"))
        self.anteriorBtn.setText(_translate("Dialog", "Anterior"))
        self.matrizEnInterfaz = [[self.FIL1COL1,self.FIL1COL2,self.FIL1COL3,self.FIL1COL4,self.FIL1COL5],
                                 [self.FIL2COL1,self.FIL2COL2,self.FIL2COL3,self.FIL2COL4,self.FIL2COL5],
                                 [self.FIL3COL1,self.FIL3COL2,self.FIL3COL3,self.FIL3COL4,self.FIL3COL5],
                                 [self.FIL4COL1,self.FIL4COL2,self.FIL4COL3,self.FIL4COL4,self.FIL4COL5],
                                 [self.FIL5COL1,self.FIL5COL2,self.FIL5COL3,self.FIL5COL4,self.FIL5COL5]]
        self.habilitarMatriz()
    def habilitarMatriz(self):
        for i in range(0,5):
            for j in range(0,5):
                self.matrizEnInterfaz[i][j].setVisible(False)

        for i in range(0,self.filas):
            for j in range(0,self.columnas):
                self.matrizEnInterfaz[i][j].setVisible(True)
                self.matrizEnInterfaz[i][j].setEnabled(False)


class Log(QtWidgets.QDialog):
    def __init__(self, parent):
        print("Entra aqui")
        print(parent.filas)
        filas = parent.filas
        columnas = parent.columnas
        QtWidgets.QDialog.__init__(self)
        print("\nPaso1...")
        self.ventana = QtWidgets.QDialog()
        print("\nPaso2")
        self.ui = Ui_Dialog()
        print("\nPaso3")
        self.ui.setupUi(self.ventana)
        self.ventana.show()